name: flutter_demo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_translate: ^4.0.4
  unicons: ^2.1.1 # https://iconscout.com/unicons/solid-icons
  auto_size_text: ^3.0.0
  animate_do: ^3.1.2
  flutter_email_sender: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
  fonts:
    - family: GochiHand-Regular
      fonts:
        - asset: assets/fonts/GochiHand-Regular.ttf
          weight: 700
