name: flutter_demo
description: "Just a Flutter app demo"

publish_to: 'none'

version: 1.0.3+1.0.3

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.1
  flutter_translate: ^4.1.0
  unicons: ^2.1.2 # some fancy icons: https://iconscout.com/unicons/solid-icons
  animate_do: ^3.3.4
  flutter_email_sender: ^6.0.3
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  google_sign_in: '^6.2.1'
  cloud_firestore: ^5.2.1
  provider: ^6.1.2
  google_mobile_ads: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  test: ^1.25.7

flutter_icons:
  android: true
  ios: false
  image_path: assets/images/icon.png
  adaptive_icon_background: assets/images/icon.png

flutter_native_splash:
  color: "#001a29"
  image: assets/resources/splash.png
  web: false
  android_gravity: center 
  fullscreen: true
  android_12:
    color: "#001a29"
    icon_background_color: "#ffffff"
    image: assets/resources/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/audio/
  fonts:
    - family: GochiHand-Regular
      fonts:
        - asset: assets/fonts/GochiHand-Regular.ttf
          weight: 700
