name: flutter_demo
description: "Just a Flutter app demo"

publish_to: 'none'

version: 1.0.2+1.0.2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_translate: ^4.0.4
  unicons: ^2.1.1 # some fancy icons: https://iconscout.com/unicons/solid-icons
  animate_do: ^3.1.2
  flutter_email_sender: ^6.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: '^6.2.1'
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  google_mobile_ads: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  test: ^1.24.9

flutter_icons:
  android: true
  ios: false
  image_path: assets/images/icon.png
  adaptive_icon_background: assets/images/icon.png

flutter_native_splash:
  color: "#001a29"
  image: assets/resources/splash.png
  web: false
  android_gravity: center 
  fullscreen: true
  android_12:
    color: "#001a29"
    icon_background_color: "#ffffff"
    image: assets/resources/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/audio/
  fonts:
    - family: GochiHand-Regular
      fonts:
        - asset: assets/fonts/GochiHand-Regular.ttf
          weight: 700
