// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm9J7Uq7ZYt2u9B0Y1H8Kz8q2vqRSWb54',
    appId: '1:927750831361:web:04ab0a90f390ab89c76f00',
    messagingSenderId: '927750831361',
    projectId: 'flutter-demo-ce7cd',
    authDomain: 'flutter-demo-ce7cd.firebaseapp.com',
    storageBucket: 'flutter-demo-ce7cd.appspot.com',
    measurementId: 'G-B7QVTM0E8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rS6tm_5aZRmW5t-MFxTCFxgmGT7W8sw',
    appId: '1:927750831361:android:950d370c9f2fb22bc76f00',
    messagingSenderId: '927750831361',
    projectId: 'flutter-demo-ce7cd',
    storageBucket: 'flutter-demo-ce7cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoao1JoCiDbR-k6A-ZBtg2_xJKf_SqiSQ',
    appId: '1:927750831361:ios:ec5f6e41caf2e02ec76f00',
    messagingSenderId: '927750831361',
    projectId: 'flutter-demo-ce7cd',
    storageBucket: 'flutter-demo-ce7cd.appspot.com',
    androidClientId: '927750831361-pk07o3dqfaufsd6hn94n4s657boqmchq.apps.googleusercontent.com',
    iosClientId: '927750831361-b8h9b27oiv5gv2qqgbo9bcpjj64veesv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoao1JoCiDbR-k6A-ZBtg2_xJKf_SqiSQ',
    appId: '1:927750831361:ios:6fdc6b85a04125c7c76f00',
    messagingSenderId: '927750831361',
    projectId: 'flutter-demo-ce7cd',
    storageBucket: 'flutter-demo-ce7cd.appspot.com',
    androidClientId: '927750831361-pk07o3dqfaufsd6hn94n4s657boqmchq.apps.googleusercontent.com',
    iosClientId: '927750831361-lrjr82fb5so9jil602dhpq0fquhqvuc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo.RunnerTests',
  );
}
